# Generated by Django 2.1.7 on 2019-08-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(help_text='정확한 장소를 입력해주세요.', max_length=200),
        ),
    ]
