# Generated by Django 2.1.7 on 2019-08-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20190808_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='areas',
            field=models.PositiveSmallIntegerField(choices=[(0, '종로구'), (1, '중구'), (2, '용산구'), (3, '성동구'), (4, '광진구'), (5, '동대문구'), (6, '중랑구'), (7, '성북구'), (8, '강북구'), (9, '도봉구'), (10, '노원구'), (11, '은평구'), (12, '서대문구'), (13, '마포구'), (14, '양천구'), (15, '강서구'), (16, '구로구'), (17, '금천구'), (18, '영등포구'), (19, '동작구'), (20, '관악구'), (21, '서초구'), (22, '강남구'), (23, '송파구'), (24, '강동구')], default=0, null=True, verbose_name='지역'),
        ),
        migrations.AddField(
            model_name='post',
            name='shows',
            field=models.PositiveSmallIntegerField(choices=[(0, '음악공연'), (1, '연극공연'), (2, '운동경기'), (3, '학술회'), (4, '기타')], default=0, null=True, verbose_name='공연'),
        ),
    ]
