# Generated by Django 2.1.7 on 2019-08-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20190808_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='areas',
            field=models.PositiveSmallIntegerField(choices=[(0, '강서구'), (1, '강남구'), (2, '강동구'), (3, '강북구'), (4, '구로구'), (5, '금천구'), (6, '관악구'), (7, '광진구'), (8, '노원구'), (9, '도봉구'), (10, '동대문구'), (11, '동작구'), (12, '마포구'), (13, '서대문구'), (14, '서초구'), (15, '성동구'), (16, '송파구'), (17, '성북구'), (18, '용산구'), (19, '양천구'), (20, '은평구'), (21, '영등포구'), (22, '종로구'), (23, '중구'), (24, '중랑구')], default=0, null=True, verbose_name='지역'),
        ),
        migrations.AlterField(
            model_name='post',
            name='shows',
            field=models.PositiveSmallIntegerField(choices=[(0, '음악공연'), (1, '연극공연'), (2, '운동경기'), (3, '학술회/전시'), (4, '기타')], default=0, null=True, verbose_name='공연'),
        ),
    ]
